### ISSUE TITLE
CSS Styles?

### ISSUE THREAD

**Issue by juancerezo** [rvagg/node-pygmentize-bundled#16]
It is not clear to me. Can pygmentize create css styles from node? If so, how do I do? :S

Thanks for your time!

**Comment by juancerezo** [comment]
Sorry to open so soon. I've found the documentation for styles.

[./vendor/pygments/doc/docs/styles.rst](https://github.com/rvagg/node-pygmentize-bundled/blob/master/vendor/pygments/doc/docs/styles.rst)

**Comment by juancerezo** [comment]
OK. I found how to generate style sheets. It is not easy, at first, for beginners. Pygments must be installed with Pip!

I use Windows:

If you have Python installed, you should. You pip have installed by default. Pip is a package manager like NPM.

Knowing this, it is simple:

`pip install pygments`

After that:

`pygmentize -S <some style> -f html > pygments.css`

**Comment by jwerre** [comment]
@juancerezo please share your stylesheet
