### ISSUE TITLE
Cannot resolve module 'child_process' in mac

### ISSUE THREAD

**Issue by AlicePrincess** [rvagg/node-pygmentize-bundled#18]
require('pygmentize-bundled') has error
Module not found: Error: Cannot resolve module 'child_process' in /Users/alice/blog-admine/node_modules/.2.3.0@pygmentize-bundled
 @ ./~/.2.3.0@pygmentize-bundled/index.js

I want to know how to solve？

**Comment by Redkill** [comment]
and in windows 10 too

**Comment by jungor** [comment]
win10 +1. But I think this is duo to 'child_process' is kind of 'build_in library' of Node，so Webpack could not resolve it. Better to doc whether this can run in browser env in README 😺 .

**Comment by fasiha** [comment]
This package is a Node-only package that calls a Python package (pygmentize) to do syntax highlighting—obviously this won’t work in browser. These days there are far better JS-only packages like [highlight.js](https://highlightjs.org/) that should work in browser and Node.

@AlicePrincess @Redkill are you trying to use this in browser? Works fine for me in Node 7.4.0, macOS.

**Comment by Redkill** [comment]
Yeah, i'm using this pakage in browser, that's for a Markdown Editor made with VueJS
