### ISSUE TITLE
child_process dependency not found

### ISSUE THREAD

**Issue by RenFontes** [rvagg/node-pygmentize-bundled#20]
Getting the following error when trying to use this.

```
This dependency was not found:

* child_process in ./~/pygmentize-bundled/index.js`
```

child_process npm package is just a place holder and has no code... =/

**Comment by luoyali** [comment]
Hello, is this problem solved ？  I have the same problem.

**Comment by rvagg** [comment]
how are you using pygmentize-bundled? are you running it directly with Node or as part of some other application? `child_process` isn't a dependency, it's a module contained in Node core itself. I don't recognise the format of your error output so you're going to have to provide more context, sorry.

**Comment by luoyali** [comment]
![image](https://user-images.githubusercontent.com/15316221/34401518-b3f54c40-ebd6-11e7-94a7-12418331ecde.png)

I use the webpck + vue-cli environment, the above screenshot is the code for my local project

**Comment by rvagg** [comment]
OK, so I guess from that you're trying to use this for a frontend component. Unfortunately that's not going to work and the reason `child_process` isn't available to you is that it's functionality that can't be emulated in a browser. pygmentize_bundled is for server-side only and it forks out to run a `python` process against the pygments utility. You'll have to find a browser-compatible JavaScript-only library that'll work for you.

https://highlightjs.org/ might be better for your usecase.

**Comment by luoyali** [comment]
ok
![image](https://user-images.githubusercontent.com/15316221/34406835-0742cb9c-ebf6-11e7-93f8-2c3d1524688d.png)
OK, I've found this highlight.js code high library. I'll adjust it for the details. Thank you.
